using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;

namespace AMZNGoDSDK.Editor
{
    internal static class FirebaseABTestConstantsGenerator
    {
        private const string Header = "// Auto-generated by AMZN GoD SDK Settings. Do not edit manually.";
        private static readonly Regex Identifier = new Regex(@"\A[A-Za-z_][A-Za-z0-9_]*\z");

        internal static string OutputPath(FirebaseSettingData settings) =>
            string.IsNullOrWhiteSpace(settings?.ABTestConstantsPath)
                ? Runtime.FirebaseSettingData.DefaultABTestConstantsPath
                : settings.ABTestConstantsPath.Replace('\\', '/');

        internal static bool Validate(FirebaseSettingData settings, out string error)
        {
            error = null;
            if (!IsValidPath(OutputPath(settings)))
                return Fail("Файл констант должен быть .cs внутри Assets, вне Editor и скрытых папок; путь без '..'.", out error);

            var names = new HashSet<string>(StringComparer.Ordinal);
            var ids = new HashSet<string>(StringComparer.Ordinal);
            if (settings?.ABTests == null) return true;
            for (int i = 0; i < settings.ABTests.Count; i++)
            {
                var test = settings.ABTests[i];
                string label = $"A/B Test #{i + 1}";
                if (test == null) return Fail($"{label}: отсутствует описание теста.", out error);
                if (!IsIdentifier(test.TestName) || test.TestName == "TestIds" || test.TestName == "TestDefaultGroups")
                    return Fail($"{label}: Test Name должен быть C# именем (латиница, цифры, '_', не с цифры), кроме TestIds / TestDefaultGroups.", out error);
                if (!names.Add(test.TestName)) return Fail($"Повторяется Test Name '{test.TestName}'.", out error);
                if (!IsIdentifier(test.TestId) || test.TestId.Length > 100)
                    return Fail($"{label}: Test ID — 1–100 символов: латиница, цифры, '_'; первый символ — буква или '_'.", out error);
                if (!ids.Add(test.TestId)) return Fail($"Повторяется Test ID '{test.TestId}'.", out error);
                if (test.GroupNames == null || test.GroupNames.Count == 0)
                    return Fail($"{label}: добавьте хотя бы одну группу.", out error);
                var groups = new HashSet<string>(StringComparer.Ordinal);
                foreach (string group in test.GroupNames)
                {
                    if (!IsIdentifier(group) || group.Length > 100 || group == test.TestName + "GroupNames")
                        return Fail($"{label}: группа '{group}' должна быть C# именем длиной до 100 символов и отличаться от имени своего класса {test.TestName}GroupNames.", out error);
                    if (!groups.Add(group)) return Fail($"{label}: повторяется группа '{group}'.", out error);
                }
                if (!groups.Contains(test.GetDefaultGroup()))
                    return Fail($"{label}: выберите существующую Default Group.", out error);
                if (test.TestId == Runtime.FirebaseSettingData.AdjustEnableTestId
                    && (groups.Count != 2 || !groups.Contains(Runtime.FirebaseSettingData.AdjustEnabledGroup)
                        || !groups.Contains(Runtime.FirebaseSettingData.AdjustDisabledGroup)
                        || test.GetDefaultGroup() != Runtime.FirebaseSettingData.AdjustEnabledGroup))
                    return Fail("Встроенный adjust_enable использует только строковые группы true / false и Default Group = true.", out error);
            }
            return true;
        }

        private static bool IsIdentifier(string value) => !string.IsNullOrEmpty(value) && Identifier.IsMatch(value);
        private static bool Fail(string message, out string error) { error = message; return false; }

        private static bool IsValidPath(string path)
        {
            if (!path.StartsWith("Assets/", StringComparison.Ordinal)
                || !path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)) return false;
            string[] parts = path.Split('/');
            foreach (string part in parts)
            {
                if (string.IsNullOrWhiteSpace(part) || part.StartsWith(".", StringComparison.Ordinal)
                    || part.EndsWith("~", StringComparison.Ordinal) || part.EndsWith(".", StringComparison.Ordinal)
                    || part != part.Trim() || part.Equals("Editor", StringComparison.OrdinalIgnoreCase)
                    || part.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0) return false;
            }
            return true;
        }

        internal static string BuildCode(FirebaseSettingData settings)
        {
            if (!Validate(settings, out var error)) throw new ArgumentException(error);
            var tests = settings?.ABTests ?? new List<Runtime.ABTestEntry>();
            var code = new StringBuilder();
            code.AppendLine(Header);
            code.AppendLine("namespace ABTesting.Generated");
            code.AppendLine("{");
            code.AppendLine("    public static class TestIds");
            code.AppendLine("    {");
            foreach (var test in tests)
                Constant(code, test.TestName, test.TestId);
            code.AppendLine("    }");
            code.AppendLine();
            code.AppendLine("    public static class TestDefaultGroups");
            code.AppendLine("    {");
            foreach (var test in tests)
                Constant(code, test.TestName, test.GetDefaultGroup());
            code.AppendLine("    }");
            foreach (var test in tests)
            {
                code.AppendLine();
                code.AppendLine($"    public static class @{test.TestName}GroupNames");
                code.AppendLine("    {");
                foreach (string group in test.GroupNames) Constant(code, group, group);
                code.AppendLine("    }");
            }
            code.AppendLine("}");
            return code.ToString();
        }

        private static void Constant(StringBuilder code, string name, string value)
        {
            // Verbatim identifiers also support keywords such as 'default', 'true' and 'false'.
            // Values are validated identifiers, so cannot introduce C# string escapes or source code.
            code.AppendLine($"        public const string @{name} = \"{value}\";");
        }

        internal static bool TrySave(FirebaseSettingData settings, string previousPath, out string error)
        {
            if (!Validate(settings, out error)) return false;
            try
            {
                string path = OutputPath(settings);
                previousPath = string.IsNullOrWhiteSpace(previousPath)
                    ? Runtime.FirebaseSettingData.DefaultABTestConstantsPath : previousPath.Replace('\\', '/');
                bool hasPrevious = IsValidPath(previousPath) && File.Exists(previousPath);
                bool moving = hasPrevious && !string.Equals(path, previousPath, StringComparison.OrdinalIgnoreCase);
                if (File.Exists(path) && !IsGenerated(path))
                    return Fail($"Файл '{path}' не создан генератором A/B-тестов. Выберите другой путь.", out error);
                if (moving && (!IsGenerated(previousPath) || File.Exists(path)))
                    return Fail("Нельзя перенести константы: старый файл не принадлежит генератору или новый путь уже занят.", out error);
                if ((settings?.ABTests == null || settings.ABTests.Count == 0) && !hasPrevious && !File.Exists(path))
                    return true; // Existing projects with no configured tests gain no generated file.

                string code = BuildCode(settings);
                Directory.CreateDirectory(Path.GetDirectoryName(path));
                if (moving)
                {
                    // Preserve the Unity asset GUID and prevent duplicate generated types after relocation.
                    AssetDatabase.Refresh();
                    string moveError = AssetDatabase.MoveAsset(previousPath, path);
                    if (!string.IsNullOrEmpty(moveError)) return Fail(moveError, out error);
                }
                if (!File.Exists(path) || File.ReadAllText(path) != code)
                    File.WriteAllText(path, code, new UTF8Encoding(false));
                return true;
            }
            catch (Exception exception) when (exception is IOException || exception is UnauthorizedAccessException || exception is ArgumentException)
            {
                return Fail($"Не удалось сохранить константы A/B-тестов: {exception.Message}", out error);
            }
        }

        private static bool IsGenerated(string path)
        {
            using (var reader = File.OpenText(path)) return reader.ReadLine() == Header;
        }
    }
}
