using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using UnityEditor;

namespace AMZNGoDSDK.Editor
{
    /// <summary>Owns the optional AppHud XML even when AppMetrica is compiled out.</summary>
    internal static class AppMetricaAppHudDependencies
    {
        internal const string DependencyName = "AppMetricaAppHudAdapterDependencies";
        internal const string FilePath = "Assets/Editor/" + DependencyName + ".xml";
        private const string TemplatePath = "Runtime/Modules/AppMetrica/Appmetrica/Runtime/Features/AppHud/Adapter/" + DependencyName + "Template.xml";
        private const string OwnerMarker = " Generated by AMZN GoD SDK: AppMetrica AppHud dependencies. Do not edit. ";
        private const string VendorMarker = "Auto generated file from AppMetrica Unity Plugin. Do not delete or change manually";

        internal static void Synchronize(bool? featureEnabled = null)
        {
            bool enabled = IsModuleEnabled() && (featureEnabled ?? ReadFeatureEnabled());
            XmlDocument existing = File.Exists(FilePath) ? LoadXml(FilePath) : null;
            if (existing != null && !IsOwned(existing))
                throw new IOException("AppHud dependency file изменён пользователем и не будет перезаписан или удалён: " +
                    FilePath + ". Перенеси собственные зависимости в отдельный XML и повторно сохрани настройки SDK.");

            if (!enabled)
            {
                if (existing != null && !AssetDatabase.DeleteAsset(FilePath))
                    throw new IOException("Не удалось удалить сгенерированную AppHud dependency: " + FilePath);
                return;
            }

            // Resolve virtual UPM paths before any filesystem access; package files stay immutable.
            string template = EdmDependencyGenerator.ResolveTemplatePath(TemplatePath);
            if (template == null) throw new FileNotFoundException("Не найден AppHud dependency template в SDK: " + TemplatePath);
            var document = LoadXml(template);
            if (document.DocumentElement?.Name != "dependencies")
                throw new InvalidDataException("AppHud template не содержит корень dependencies: " + template);
            document.InsertBefore(document.CreateComment(OwnerMarker), document.DocumentElement);
            string content = document.OuterXml;
            if (existing != null && existing.OuterXml == content) return;
            Directory.CreateDirectory(Path.GetDirectoryName(FilePath));
            File.WriteAllText(FilePath, content, new UTF8Encoding(false));
            AssetDatabase.ImportAsset(FilePath);
        }

        internal static void CollectValidationErrors(ICollection<string> errors)
        {
            try
            {
                bool enabled = IsModuleEnabled() && ReadFeatureEnabled();
                if (!File.Exists(FilePath))
                {
                    if (enabled) errors.Add("AppMetrica AppHud: отсутствует сгенерированный EDM XML " + FilePath + ".");
                    return;
                }
                var document = LoadXml(FilePath);
                if (!IsOwned(document))
                    errors.Add("AppMetrica AppHud: SDK не может управлять изменённым вручную XML " + FilePath +
                        ". Перенеси собственные зависимости в отдельный XML и повторно сохрани SDK Settings.");
                else if (!enabled)
                    errors.Add("AppMetrica AppHud: EDM XML остаётся активным при выключенном SDK, модуле или feature: " + FilePath + ".");
                else
                {
                    string template = EdmDependencyGenerator.ResolveTemplatePath(TemplatePath);
                    if (template == null || document.DocumentElement?.OuterXml != LoadXml(template).DocumentElement?.OuterXml)
                        errors.Add("AppMetrica AppHud: EDM XML не соответствует текущему шаблону SDK: " + FilePath + ".");
                }
            }
            catch (Exception exception)
            {
                errors.Add("AppMetrica AppHud: не удалось проверить EDM dependencies: " + exception.Message);
            }
        }

        private static bool IsModuleEnabled() =>
            ModuleDefineManager.IsModuleEnabled(ModuleDefineManager.SDK_ENABLED_DEFINE) &&
            ModuleDefineManager.IsModuleEnabled(ModuleDefineManager.APPMETRICA_DEFINE);

        private static bool ReadFeatureEnabled()
        {
            const string path = "ProjectSettings/AppMetricaSettings.xml";
            if (!File.Exists(path)) return false;
            var document = LoadXml(path);
            var value = document.SelectSingleNode("/appMetricaSettings/appMetricaSetting[@name='Feature.AppHudAdapter.Enabled']/@value")?.Value;
            return value == "Manual" || value == "True" || value == "Auto";
        }

        private static bool IsOwned(XmlDocument document)
        {
            bool vendorGenerated = false;
            foreach (XmlNode node in document.ChildNodes)
            {
                if (node.NodeType != XmlNodeType.Comment) continue;
                if (node.Value == OwnerMarker) return true;
                if (node.Value == VendorMarker) vendorGenerated = true;
            }
            if (!vendorGenerated) return false;

            // Migrate only the two exact legacy generated payloads shipped by the SDK.
            // A familiar filename or Maven coordinate alone does not establish ownership.
            string payload = document.DocumentElement?.OuterXml;
            return payload == LegacyPayload("8.5.1", "1.1.2") || payload == LegacyPayload("7.12.0", "1.0.0");
        }

        private static string LegacyPayload(string androidVersion, string iosVersion) =>
            "<dependencies><androidPackages><androidPackage spec=\"io.appmetrica.analytics:analytics-apphud:" + androidVersion +
            "\" /></androidPackages><iosPods><iosPod name=\"AppMetricaApphudAdapter\" version=\"" + iosVersion +
            "\" /></iosPods></dependencies>";

        private static XmlDocument LoadXml(string path)
        {
            var document = new XmlDocument { XmlResolver = null };
            using (var reader = XmlReader.Create(path, new XmlReaderSettings { DtdProcessing = DtdProcessing.Prohibit }))
                document.Load(reader);
            return document;
        }
    }
}
