using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Xml;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace AMZNGoDSDK.Editor
{
    /// <summary>
    /// Генератор сводного EDM4U Dependencies.xml из шаблонов включённых модулей.
    ///
    /// Заменяет DependencyPreprocessor, который на каждом билде делал
    /// File.Move XML → .disabled ВНУТРИ папки SDK: в immutable UPM-пакете это
    /// гарантированный IOException, а Cross-Promo XML он не покрывал вовсе.
    ///
    /// Схема:
    /// - исходные XML модулей переименованы в *Template.xml — EDM их не видит
    ///   (резолвер матчит только файлы *Dependencies.xml в Editor-папках);
    /// - при каждом применении тогглов (ModuleDefineManager.UpdateDefineSymbols /
    ///   RemoveAllSdkDefines) и перед билдом (страховочный IPreprocessBuildWithReport)
    ///   из шаблонов ВКЛЮЧЁННЫХ модулей собирается единый
    ///   Assets/AMZNGoDSDKGenerated/Editor/AmznGoDSdkDependencies.xml.
    ///   Файл живёт в Assets потребителя, вне папки SDK — схема работает и при
    ///   классической поставке в Assets, и из immutable-пакета.
    /// </summary>
    public static class EdmDependencyGenerator
    {
        public const string GeneratedFolder = "Assets/AMZNGoDSDKGenerated/Editor";
        public const string GeneratedFilePath = GeneratedFolder + "/AmznGoDSdkDependencies.xml";

        /// <summary>
        /// define модуля → шаблон его EDM-зависимостей (путь относительно корня SDK).
        /// У модуля может быть несколько шаблонов (Cross-Promo).
        ///
        /// Вне реестра намеренно:
        /// - Firebase — шаблона нет: в модуле только FirebaseModule.cs, нативные
        ///   Firebase-зависимости потребитель ставит сам; при появлении XML — добавить;
        /// - AppMetricaAppHudAdapterDependencies.xml — фича-адаптер, его копирует в
        ///   Assets/Editor собственный механизм AppMetrica
        ///   (AppMetricaResolver.UpdateDependencyState) по тогглу фичи;
        /// - IAP, InternetConnection, InGameDebugConsole, Analytics — EDM-зависимостей
        ///   не имеют (IAP — vendored jar'ы).
        /// </summary>
        private static readonly (string define, string templateRelPath)[] Templates =
        {
            (ModuleDefineManager.ADJUST_DEFINE,     "Runtime/Modules/Adjust/Adjust/Native/Editor/AdjustDependenciesTemplate.xml"),
            (ModuleDefineManager.APPMETRICA_DEFINE, "Runtime/Modules/AppMetrica/Appmetrica/Editor/AppMetricaDependenciesTemplate.xml"),
            (ModuleDefineManager.CROSSPROMO_DEFINE, "Runtime/Modules/Cross-Promo/EagleExoPlayer/Editor/EagleExoPlayerDependenciesTemplate.xml"),
            (ModuleDefineManager.CROSSPROMO_DEFINE, "Runtime/Modules/Cross-Promo/VideoPlayer/Editor/ExoPlayerDependenciesTemplate.xml"),
        };

        /// <summary>
        /// Перегенерирует сводный XML по актуальному состоянию defines.
        /// Если ни один модуль с зависимостями не включён — удаляет сгенерированный файл.
        /// Никогда не роняет вызывающий код: любые ошибки — warning в консоль.
        /// </summary>
        public static void Regenerate()
        {
            try
            {
                RegenerateInternal();
            }
            catch (Exception e)
            {
                Debug.LogWarning($"[AMZN GoD SDK] EDM dependencies generation failed: {e.Message}");
            }
        }

        private static void RegenerateInternal()
        {
            var output = new XmlDocument();
            output.AppendChild(output.CreateXmlDeclaration("1.0", "utf-8", null));
            output.AppendChild(output.CreateComment(
                " Auto-generated by AMZN GoD SDK from module dependency templates. " +
                "Do not edit: the file is regenerated when SDK module toggles change and before every build. "));
            var root = output.CreateElement("dependencies");
            output.AppendChild(root);

            // Группы верхнего уровня (androidPackages, iosPods, …) — по одной на имя.
            var groups = new Dictionary<string, XmlElement>(StringComparer.Ordinal);
            bool hasContent = false;

            foreach (var (define, templateRelPath) in Templates)
            {
                if (!ModuleDefineManager.IsModuleEnabled(define))
                    continue;

                string physicalPath = ResolveTemplatePath(templateRelPath);
                if (physicalPath == null)
                {
                    // Папка модуля может отсутствовать (урезанная поставка) — не ошибка.
                    continue;
                }

                var template = new XmlDocument();
                template.Load(physicalPath);

                var templateRoot = template.DocumentElement;
                if (templateRoot == null || templateRoot.Name != "dependencies")
                {
                    Debug.LogWarning($"[AMZN GoD SDK] EDM template has no <dependencies> root, skipped: {templateRelPath}");
                    continue;
                }

                foreach (XmlNode groupNode in templateRoot.ChildNodes)
                {
                    if (!(groupNode is XmlElement groupEl))
                        continue;

                    if (!groups.TryGetValue(groupEl.Name, out var outGroup))
                    {
                        outGroup = output.CreateElement(groupEl.Name);
                        root.AppendChild(outGroup);
                        groups[groupEl.Name] = outGroup;
                    }

                    foreach (XmlNode child in groupEl.ChildNodes)
                    {
                        if (!(child is XmlElement))
                            continue; // комментарии шаблонов в сводный файл не тащим

                        outGroup.AppendChild(output.ImportNode(child, true));
                        hasContent = true;
                    }
                }
            }

            if (!hasContent)
            {
                DeleteGeneratedFile();
                return;
            }

            WriteIfChanged(Serialize(output));
        }

        private static string ResolveTemplatePath(string templateRelPath)
        {
            foreach (var rootPrefix in NativePluginRegistry.SdkRootPrefixes)
            {
                // GetPhysicalPath резолвит виртуальные Packages/-пути в PackageCache;
                // для Assets/-путей возвращает их как есть.
                string physical = FileUtil.GetPhysicalPath(rootPrefix + templateRelPath);
                if (!string.IsNullOrEmpty(physical) && File.Exists(physical))
                    return physical;
            }

            return null;
        }

        private static string Serialize(XmlDocument doc)
        {
            var settings = new XmlWriterSettings
            {
                Indent = true,
                IndentChars = "    ",
            };

            // XmlWriter поверх StringBuilder/StringWriter пишет декларацию по
            // Encoding самого writer'а (для StringWriter это UTF-16) — подменяем,
            // чтобы декларация совпадала с фактической UTF-8 записью на диск.
            using (var writer = new Utf8StringWriter())
            {
                using (var xmlWriter = XmlWriter.Create(writer, settings))
                {
                    doc.Save(xmlWriter);
                }

                return writer.ToString();
            }
        }

        private sealed class Utf8StringWriter : StringWriter
        {
            public override Encoding Encoding => Encoding.UTF8;
        }

        private static void WriteIfChanged(string content)
        {
            // Не переписываем файл без изменений — чтобы не дёргать импорт и EDM-резолв.
            if (File.Exists(GeneratedFilePath) && File.ReadAllText(GeneratedFilePath) == content)
                return;

            Directory.CreateDirectory(GeneratedFolder);
            File.WriteAllText(GeneratedFilePath, content);
            AssetDatabase.ImportAsset(GeneratedFilePath);
            Debug.Log($"[AMZN GoD SDK] Generated EDM dependencies: {GeneratedFilePath}");
        }

        private static void DeleteGeneratedFile()
        {
            if (!File.Exists(GeneratedFilePath))
                return;

            AssetDatabase.DeleteAsset(GeneratedFilePath);
            Debug.Log($"[AMZN GoD SDK] Removed generated EDM dependencies (no enabled modules with dependencies): {GeneratedFilePath}");
        }
    }

    /// <summary>
    /// Страховка на случай билда без открытия SDK Settings: синхронизирует defines
    /// с конфигом (как делал DependencyPreprocessor) — что в свою очередь
    /// перегенерирует сводный EDM XML и обновляет build-фильтр нативных плагинов.
    /// </summary>
    public class EdmDependencyBuildPreprocessor : IPreprocessBuildWithReport
    {
        public int callbackOrder => -100; // раньше остальных препроцессоров SDK

        public void OnPreprocessBuild(BuildReport report)
        {
            var settings = SdkSettingsManager.LoadSettings();
            ModuleDefineManager.UpdateDefineSymbols(settings);
        }
    }
}
